# Generated by Django 6.0.3 on 2026-03-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_gender_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='purpose',
            field=models.CharField(choices=[('wallet_topup', 'Wallet topup'), ('ride', 'Ride'), ('parcel', 'Parcel'), ('food', 'Food'), ('ecommerce', 'Ecommerce'), ('tour', 'Tour'), ('room', 'Room')], max_length=20),
        ),
    ]
